### ISSUE TITLE
Add --empty and --replace options

### ISSUE THREAD

**Issue by Pajn** [wjohnsto/tsconfig-glob#1]
I have two small feature requests:

`--empty`:
Should output an tsconfig.json with an empty files array. Use case is to use it in a pre-commit hook to git so one only checks in a tsconfig.json with an empty files array and avoids conflicts just because files were added, removed or moved.

`--replace`:
Should replace all files in the files array and not keep the previous ones. Use case is to avoid old files hanging around in the files array when only using the filesGlob array.

**Comment by wjohnsto** [comment]
@Pajn I'm wondering if the `--replace` option should be the default behavior. If you are using the filesGlob array, you should always be able to replace what is in the files array.

`--empty` looks good, I will merge it in soon.

**Comment by asgerhallas** [comment]
+1 for making `--replace` default behavior :)

**Comment by wjohnsto** [comment]
This is merged in and published. `replace` is true by default, use `--no-replace` to turn it off.  :+1:
