### ISSUE TITLE
Ordering files "by glob"

### ISSUE THREAD

**Issue by asgerhallas** [wjohnsto/tsconfig-glob#3]
I wonder if it is possible to populate the files-array , so the files is in the same order as the glob-matches, like if I do:

```
filesGlob: [ "/a/*.ts", "/b/*.ts" ]
```

it would result in:

   files: [ "/a/1.ts", "/a/2.ts", "/b/1.ts" ]

and so on. 

That would be very useful for making sure dependencies got emitted in the right order when using `--out`.

**Comment by wjohnsto** [comment]
This is definitely possible. I'm working on getting some tests up, and I would want to finish that before I add this feature.

**Comment by henryptung** [comment]
+1 to this. Because the `tsconfig.json` is checked in for us, there's a lot of churn in that file any time something changes (and sometimes when nothing changes), so the Git history for that file is basically useless until we have a consistent ordering.

**Comment by brahms** [comment]
Hey, I made a quick PR for this fix, it still keeps files sorted by their file type, but makes sure before entering that function they are already sorted by alpha.

**Comment by wjohnsto** [comment]
Fixed in [v0.3.0](https://github.com/wjohnsto/tsconfig-glob/releases/tag/v0.3.0)

**Comment by asgerhallas** [comment]
Sorry for going silent on this one. That is great news. I'll check it out!

**Comment by ajaegle** [comment]
I'm using version 4.1.0 and having some issues concerning the order - especially as this behaves differently to the way the atom-typescript plugin does the rewriting.

```
    "filesGlob": [
        "./app/**/*.ts",
        "./typings/browser.d.ts",
        "!./node_modules/**/*"
    ],
```

Results in:

```
       "files": [
          "./typings/browser.d.ts",
           "./app/base/first.ts",
           "./app/base/second.ts",
           ...
         ]
```

If I correctly understand this issue, this should have been fixed to behave deterministicly, right?

**Comment by henryptung** [comment]
@ajaegle The sort order priority is something like this:
1. tsd.d.ts
2. All other *.d.ts files (sorted)
3. All other files (sorted)

The order you gave does seem consistent with this; do you need a different order?

**Comment by wjohnsto** [comment]
I'm not sure about the behavior of atom-typescript. The initial thought with sorting the `.d.ts` files was because earlier versions of TS read the files in-order and wouldn't get the typings unless they were at the top. I think this has been resolved.

Another benefit of sorting was to prevent the `tsconfig.json` from changing unless it has to. This helps with commits so that you are not constantly finding merge conflicts with the `tsconfig.json`.

It does appear as though it is possible to stop sorting `.d.ts` files to the top of the list, so if this is what people want then I can make it happen.

**Comment by fernandomora** [comment]
+1 to use same sorting that atom-typescript.
When some people use atom-typescript and others tsconfig-glob, each time a team member updates tsconfig.json, files order is changed and git history gets dirty.
