### ISSUE TITLE
Manually added files are removed even with --replace

### ISSUE THREAD

**Issue by masimplo** [wjohnsto/tsconfig-glob#5]
Hi there,

I just found out about your module after struggling to get tsc and tslint to play well with globs. I am facing an issue where I have entered the typing file paths in "files" property of tsconfig.json but as soon as I run the tsconfig cli the files array is populated with the correct file but .d.ts files are gone.

tsconfig.json before running your tool looks like:

```
    "files": [
        "node/node.d.ts",
        "tape/tape.d.ts",
        "express/express.d.ts",
        "mime/mime.d.ts",
        "serve-static/serve-static.d.ts",
        "superagent/superagent.d.ts",
        "supertest/supertest.d.ts"
    ],
    "filesGlob": [
        "src/**/*.ts",
        "spec/**/*.ts",
        "e2e/**/*.ts"
    ]
```

and after running the tool:

```
    "files": [
        "src/greeter.ts",
        "src/index.ts",
        "spec/greeter-spec.ts",
        "e2e/app.ts"
    ],
    "filesGlob": [
        "src/**/*.ts",
        "spec/**/*.ts",
        "e2e/**/*.ts"
    ]
```

Note that I am not providing the --replace flag.

**Comment by masimplo** [comment]
Just an update, I found in the closed issues that replace has become the default behaviour and --replace has been replaced with --no-replace. 
Providing --no-replace has same effect though.

**Comment by wjohnsto** [comment]
I will look into this, thank you for letting me know!

**Comment by wjohnsto** [comment]
I have made the decision to completely remove this feature, as it can cause the files array to be unstable. If you're using tsconfig-glob, you should put all the files you want to include in your `filesGlob` array.

Instead of this:

```
"files": [
    "node/node.d.ts",
    "tape/tape.d.ts",
    "express/express.d.ts",
    "mime/mime.d.ts",
    "serve-static/serve-static.d.ts",
    "superagent/superagent.d.ts",
    "supertest/supertest.d.ts"
],
"filesGlob": [
    "src/**/*.ts",
    "spec/**/*.ts",
    "e2e/**/*.ts"
]
```

Do this:

```
"files": [
],
"filesGlob": [
    "node/node.d.ts",
    "tape/tape.d.ts",
    "express/express.d.ts",
    "mime/mime.d.ts",
    "serve-static/serve-static.d.ts",
    "superagent/superagent.d.ts",
    "supertest/supertest.d.ts",
    "src/**/*.ts",
    "spec/**/*.ts",
    "e2e/**/*.ts"
]
```

Otherwise things get difficult to track when files are removed from a project, but are still in the `files` array.
