### ISSUE TITLE
tsconfig-glob 0.3.1 corrupts tsconfig.json by removing final EOL character

### ISSUE THREAD

**Issue by rob3c** [wjohnsto/tsconfig-glob#6]
First, thanks for this wonderfully convenient module! I use with this gulp watch task in VSCode all the time.
This file watcher code works fine in tsconfig-glob 0.2.1, but fails in 0.3.1 (at least on Windows):

```
'use strict';
var gulp = require('gulp');
var tsConfig = require('tsconfig-glob');

gulp.task('tsconfig:filesGlob', function tsconfigGlob() {
    return tsConfig({
        configPath: '.',
        cwd: process.cwd(),
        indent: 4
    }, function (err) {
        if (err) {
            console.log('[tsConfig - err] ' + JSON.stringify(err));
        }
    });
});

gulp.task('watch', [ 'tsconfig:filesGlob' ], function watch() {
    var tsConfigFile = require('./tsconfig.json');
    gulp.watch(tsConfigFile.filesGlob, [ 'tsconfig:filesGlob' ])
        .on('change', reportTSConfigFileChange);
});

function reportTSConfigFileChange(event) {
    console.log('File "' + event.path + '" was ' + event.type + '.');
}
```

The `require('./tsconfig.json')` call fails because `tsconfig-glob` removes the final EOL after the closing curly brace at the end of the file after it updates the files section in the tsconfig:filesGlob task that watch depends on. This causes node to throw the following SyntaxError "Unexpected end of input":

```
c:\project>gulp watch
[12:05:44] Using gulpfile c:\project\gulpfile.js
[12:05:44] Starting 'tsconfig:filesGlob'...
[12:05:44] Finished 'tsconfig:filesGlob' after 27 ms
[12:05:44] Starting 'watch'...
[12:05:44] 'watch' errored after 5.63 ms
[12:05:44] SyntaxError: c:\project\tsconfig.json: Unexpected end of input
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:486:27)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Gulp.watch (c:\project\gulpfile.js:18:24)
    at module.exports (c:\project\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (c:\project\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (c:\project\node_modules\orchestrator\index.js:214:10)
```

My workaround is to just use 0.2.1 in all projects for now.

**Comment by wjohnsto** [comment]
Wow, good catch. I will fix this immediately!

**Comment by wjohnsto** [comment]
The fix is in [v0.3.2](https://github.com/wjohnsto/tsconfig-glob/releases/tag/v0.3.2)

**Comment by rob3c** [comment]
Thanks for the quick fix! Unfortunately, I jumped to conclusions prematurely about the cause. It turns out the real cause was a race condition, but I'm happy the final EOL is there anyway :)

Here's a working gulpfile for 0.3.1 & 0.3.2:

```
'use strict';

var gulp = require('gulp');
var tsConfig = require('tsconfig-glob');

gulp.task('tsconfig:filesGlob', function tsconfigGlob(callback) {
    tsConfig({
        configPath: '.',
        cwd: process.cwd(),
        indent: 4
    }, callback);
});

gulp.task('watch', [ 'tsconfig:filesGlob' ], function watch() {
    var tsConfigFile = require('./tsconfig.json');

    console.log('[watch] tsConfigFile: ' + JSON.stringify(tsConfigFile, null, 4));

    gulp.watch(tsConfigFile.filesGlob, [ 'tsconfig:filesGlob' ])
        .on('change', reportTSConfigFileChange);
});

function reportTSConfigFileChange(event) {
    console.log('File "' + event.path + '" was ' + event.type + '.');
}
```

In my `tsconfig:filesGlob` task using the 0.2.1 version, I could just return the result of `tsConfig({...})` and it would be guaranteed to be finished before the watch task fires.
However, with 0.3.1/2, I need to manage the callback explicitly. Otherwise, it'll return while it's in the middle of writing the new file, and the watch task will see a corrupted `tsconfig.json` when it requires it and complains of a syntax error.

**Comment by wjohnsto** [comment]
Oh yes, I used to use fs.writeFileSync, but switched to fs.writeFile just to get away from synchronous calls.

EDIT: I made a formal [release](https://github.com/wjohnsto/tsconfig-glob/releases/tag/v0.3.0) and outlined the breaking changes

**Comment by wjohnsto** [comment]
I'm wondering if it might be nice to provide a stream-able method for use with gulp. Right now tsconfig-glob and [tsconfig-lint](/wjohnsto/tsconfig-lint) are meant to be used primarily from the command-line (or npm scripts), but a minor addition could make it easier to use with gulp and other stream-based task runners (grunt is probably SOL).
