### ISSUE TITLE
Unicode BOM in tsconfig.json causes a syntax error

### ISSUE THREAD

**Issue by ryohpops** [wjohnsto/tsconfig-glob#8]
If tsconfig.json is saved in "UTF-8 with BOM", running `tsconfig .` puts an error:
`[SyntaxError: Unexpected token ・]` (the character ・ will be hidden when copied from console)

This problem could be solved by changing tsconfig.json encoding, but I believe UTF-8 with BOM is the default encoding of a file created by Visual Studio, so I think this is worth fixed.

**Comment by stevehipwell** [comment]
We're having the same issue. +1

**Comment by wjohnsto** [comment]
Looking into this!
